// This file is automatically generated by code; do not manually update
// Last updated on 2024-02-11T20:50:52.495Z
// SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity 0.8.22;

import { VersionedContract } from "@cobuild/utility-contracts/src/version/VersionedContract.sol";


/// @title VersionedContract
/// @notice Base contract for versioning contracts
contract VersionedContract is IVersionedContract {
    /// @notice The version of the contract
    function contractVersion() external pure override returns (string memory) {
        return "0.10.1";
    }
}
