[profile.default]
auto_detect_solc = true
fs_permissions = [
    {access = "read", path = "./addresses"}, 
    {access = "read", path = "./package.json"}, 
    { access = "read-write", path = "./deploys"}
]
allow_paths = ["../../node_modules"]
fuzz_runs = 500
libs = ['node_modules', 'script', '../../node_modules']
optimizer = true
optimizer_runs = 50
via_ir = true
out = 'out'
script = 'script'
src = 'src'

[profile.dev]
optimizer = false 
optimizer_runs = 0  
via_ir = false

[fmt]
bracket_spacing = true
func_attrs_with_params_multiline = true
int_types = "long"
line_length = 120
quote_style = "double"
tab_width = 4

[invariant]
call_override = false
depth = 20
fail_on_revert = true
runs = 1000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
