// This file is automatically generated by code; do not manually update
// Last updated on 2024-05-22T23:53:19.016Z
// SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity ^0.8.23;

import { IVersionedContract } from "@cobuild/utility-contracts/src/interfaces/IVersionedContract.sol";

/// @title RevolutionGrantsVersion
/// @notice Base contract for versioning contracts
contract RevolutionGrantsVersion is IVersionedContract {
    /// @notice The version of the contract
    function contractVersion() external pure override returns (string memory) {
        return "0.7.0";
    }
}
