// This file is automatically generated by code; do not manually update
// Last updated on 2024-02-06T00:18:57.119Z
// SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity 0.8.22;

import { IVersionedContract } from "../interfaces/IVersionedContract.sol";

/// @title VersionedContract
/// @notice Base contract for versioning contracts
contract VersionedContract is IVersionedContract {
    /// @notice The version of the contract
    function contractVersion() external pure override returns (string memory) {
        return "0.3.16";
    }
}
