on:
  workflow_call:
    inputs:
      package_folder:
        required: true
        type: string

jobs:
  check:
    strategy:
      fail-fast: true

    name: Contract sizes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install node deps and foundry
        uses: ./.github/actions/setup_deps

      - name: Cache build
        uses: ./.github/actions/cache_foundry_build
        with:
          package_folder: ${{ inputs.package_folder }}

      - name: Check contract sizes
        run: cd ${{ inputs.package_folder }} && pnpm run build:sizes
