name: "Contracts"

on:
  push:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  contracts-protocol-rewards:
    name: Protocol Rewards
    uses: ./.github/workflows/protocol_rewards.yml
    secrets: inherit

  contracts-revolution:
    name: Revolution Contracts
    uses: ./.github/workflows/revolution_contracts.yml
    secrets: inherit
