name: Lint
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install node deps and foundry
        uses: ./.github/actions/setup_deps

      - name: Run prettier
        run: turbo run lint
