on:
  workflow_call:
    inputs:
      package_folder:
        required: true
        type: string

jobs:
  analyze:
    runs-on: revolution-protocol
    steps:
      - uses: actions/checkout@v3

      - name: Install node deps and foundry
        uses: ./.github/actions/setup_deps

      - uses: crytic/slither-action@v0.3.0
        with:
          fail-on: "medium"
          target: "${{ inputs.package_folder }}/src"
          slither-config: "../config/slither.config.json"
          slither-args: --solc-remaps "ds-test=${{ inputs.package_folder }}/node_modules/ds-test/src forge-std=${{ inputs.package_folder }}/node_modules/forge-std/src @openzeppelin/contracts=${{ inputs.package_folder }}/node_modules/@openzeppelin/contracts @openzeppelin/contracts-upgradeable=${{ inputs.package_folder }}/node_modules/@openzeppelin/contracts-upgradeable solmate=${{ inputs.package_folder }}/node_modules/solmate/src @cobuilding/protocol-rewards=packages/protocol-rewards" --checklist --filter-paths "@openzeppelin|ERC721|Votes|VotesUpgradeable|ERC1967Upgrade|ERC20Upgradeable.sol"
