name: Slither Analysis
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "*"

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crytic/slither-action@v0.3.0
        with:
          fail-on: "medium"
          target: "packages/revolution-contracts/src"
          slither-args: --solc-remaps "ds-test=../../../node_modules/ds-test/src/,forge-std=../../../node_modules/forge-std/src/,@openzeppelin/contracts=../../../node_modules/@openzeppelin/contracts/,@openzeppelin/contracts-upgradeable=../../../node_modules/@openzeppelin/contracts-upgradeable,solmate=../../../node_modules/solmate/src,@collectivexyz/protocol-rewards/src=../../../node_modules/@collectivexyz/protocol-rewards/src/" --checklist --show-ignored-findings --filter-paths "@openzeppelin|ERC721|Votes.sol"
