on:
  workflow_call:
    inputs:
      package_folder:
        required: true
        type: string

jobs:
  forge_test:
    strategy:
      fail-fast: true

    name: Forge test
    runs-on: revolution-protocol
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install node deps and foundry
        uses: ./.github/actions/setup_deps

      - name: Load foundry cache
        uses: ./.github/actions/cache_foundry_build
        with:
          package_folder: ${{ inputs.package_folder }}

      - name: Test
        run: |
          cd ${{ inputs.package_folder}} && pnpm clean && pnpm test

      - name: Run Geiger Check
        run: |
          forge geiger --check ${{ inputs.package_folder }}/src*
        id: geiger
