name: forge tests

on:
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  forge_test:
    strategy:
      fail-fast: true

    name: revolution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install node deps and foundry
        uses: ./.github/actions/setup_dependencies

      - name: Run protocol-rewards tests
        run: |
          cd packages/protocol-rewards && pnpm clean && pnpm test

      - name: Run revolution-contracts tests
        run: |
          cd packages/revolution-contracts && pnpm clean && pnpm test

      - name: Run Geiger Check
        run: |
          forge geiger --check packages/revolution-contracts*
        id: geiger
